// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/aws/aws-sdk-go/service/s3"
	"go.mongodb.org/mongo-driver/mongo"
	mongo2 "pixstall-file/app/file/acl/repo/mongo"
	"pixstall-file/app/file/delivery/gRPC"
	http2 "pixstall-file/app/file/delivery/http"
	"pixstall-file/app/file/repo/aws-s3"
	"pixstall-file/app/file/usecase"
	"pixstall-file/app/image/delivery/http"
	"pixstall-file/app/image/image-processing/repo/imaging"
)

// Injectors from wire.go:

func InitImageController(db *mongo.Database, awsS3 *s3.S3) http.ImageController {
	repo := aws_s3.NewAWSS3FileRepository(awsS3)
	aclRepo := mongo2.NewMongoFileAclRepo(db)
	image_processingRepo := imaging.NewImagingImageProcessingRepo()
	useCase := usecase.NewFileUseCase(repo, aclRepo, image_processingRepo)
	imageController := http.NewImageController(useCase)
	return imageController
}

func InitFileStoreService(db *mongo.Database, awsS3 *s3.S3) gRPC.FileService {
	repo := aws_s3.NewAWSS3FileRepository(awsS3)
	aclRepo := mongo2.NewMongoFileAclRepo(db)
	image_processingRepo := imaging.NewImagingImageProcessingRepo()
	useCase := usecase.NewFileUseCase(repo, aclRepo, image_processingRepo)
	fileService := gRPC.NewFileService(useCase)
	return fileService
}

func InitFileController(db *mongo.Database, awsS3 *s3.S3) http2.FileController {
	repo := aws_s3.NewAWSS3FileRepository(awsS3)
	aclRepo := mongo2.NewMongoFileAclRepo(db)
	image_processingRepo := imaging.NewImagingImageProcessingRepo()
	useCase := usecase.NewFileUseCase(repo, aclRepo, image_processingRepo)
	fileController := http2.NewFileController(useCase)
	return fileController
}
